/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

public class WebSpinner {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new WebSpinner().getGreeting());
    }
}
