/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WebSpinnerTest {
    @Test void appHasAGreeting() {
        WebSpinner classUnderTest = new WebSpinner();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
